apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app-deployment
  namespace: py-app
  labels:
    app: py-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app-container
        image: tpchungg/py_app:d33ea73e5df6e029ca9926556ca41e7d78891ca5
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080 