apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app-deployment
  namespace: py-app
  labels:
    app: py-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app-container
        image: tpchungg/py_app:4ef1bfa81c48ddbafc7a7567a9017ef5bcfd67f6
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080 