apiVersion: v1
kind: Service
metadata:
  name: py-app-service
  namespace: py-app
spec:
  type: LoadBalancer 
  selector:
    app: py-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8000 